apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-a
  template:
    metadata:
      labels:
        app: microservice-a
    spec:
      containers:
      - name: microservice-a
        image: samukamaciel/avancadev-ms-01
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9090
        
        env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: microservico-secret
                  key: RABBITMQ_DEFAULT_USER

            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: microservico-secret
                  key: RABBITMQ_DEFAULT_PASS

            - name: RABBITMQ_DEFAULT_HOST
              value: rabbitmq-service

      volumes:
        - name: microservico-conf
          configMap:
            name: microservico-conf
            items:
              - key: env
                path: .env
              