apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-b
  template:
    metadata:
      labels:
        app: microservice-b
    spec:
      containers:
      - name: microservice-b
        image: samukamaciel/avancadev-ms-02

        env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: microservico-secret
                  key: RABBITMQ_DEFAULT_USER

            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: microservico-secret
                  key: RABBITMQ_DEFAULT_PASS

            - name: RABBITMQ_DEFAULT_HOST
              value: rabbitmq-service

            - name: URL_MS_03
              value: microservice-c

      volumes:
        - name: microservico-conf
          configMap:
            name: microservico-conf
            items:
              - key: env
                path: .env
