apiVersion: v1
kind: Service
metadata:
  name: microservice-a
spec:
  type: LoadBalancer
  selector:
    app: microservice-a
  ports:
    - port: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: microservice-b-service
spec:
  selector:
    app: microservice-b
  ports:
    - protocol: TCP
      port: 9091
      targetPort: 9091

---

apiVersion: v1
kind: Service
metadata:
  name: microservice-c
spec:
  selector:
    app: microservice-c
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092 

---

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  labels:
    app: rabbitmq-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 15672
      nodePort: 30081
    - name: amqp
      protocol: TCP
      port: 5672
      nodePort: 30082
  selector:
    app: rabbitmq